Use credentials plugin for managing authentication credentials
jenkinsci/confluence-publisher-plugin pull request #103
Opened 2023-03-23 16:37 UTC by ccHanibal

As discussed in #102 this PR makes the plugin use the credentials plugin for managing credentials to confluence sites.
Existing credentials are migrated automatically on jenkins launch.
Support for other credentials than username and password is not yet included (will come with a future PR).

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2023-03-23 17:23 UTC, jetersen commented
I'd suggest adding the token bearer authentication in the same PR to reduce rework.

2023-03-23 17:32 UTC, jetersen requested changes

2023-03-23 17:32 UTC, jetersen commented on src/main/java/com/myyearbook/hudson/plugins/confluence/ConfluenceSite.java
> +    public ConfluenceSite(URL url, final String credentialsId) {
This breaks binary compatibility.

I suggest you create a new constructor and remove `@DataBoundConstructor` from this one mark this one deprecated.

So create a new constructor marked with `@DataBoundConstructor` that takes no arguments and then create a `@DataBoundSetter` for `url` and `credentialsId`

See why here: https://www.jenkins.io/doc/developer/plugin-development/pipeline-integration/#constructor-vs-setters

```java
    /**
     * 
     *
     * @deprecated use {@link #new()} instead.  
     */
    @Deprecated
    public ConfluenceSite(URL url, final String username, final String password) {
        if (!url.toExternalForm().endsWith("/")) {
            try {
                url = new URL(url.toExternalForm() + "/");
            } catch (MalformedURLException e) {
                throw new AssertionError(e); // impossible
            }
        }

        this.url = url;
        this.username = hudson.Util.fixEmptyAndTrim(username);
        this.password = Secret.fromString(password);
    }

    @DataBoundConstructor
    public ConfluenceSite() {
    }
    
    /* ... you have these further below already */
    
    @DataBoundSetter
    public void setUrl(@CheckForNull URL url) {
        this.url = Util.fixEmptyAndTrim(url);
    }
    
    @DataBoundSetter
    public void setUrl(@CheckForNull String credentialsId) {
        this.credentialsId = Util.fixEmptyAndTrim(credentialsId);
    }
```

2023-03-23 17:32 UTC, jetersen commented on src/main/java/com/myyearbook/hudson/plugins/confluence/ConfluenceSite.java
> +
I don't think you should add these as they would be considered obsolete and will be hard to remove once added.

Also they definitely should not have `@DataBoundSetter` when transient.

```suggestion
```

2023-03-23 18:40 UTC, ccHanibal commented on src/main/java/com/myyearbook/hudson/plugins/confluence/ConfluenceSite.java
> +                if (credentials instanceof UsernamePasswordCredentials) {
They are both interfaces.

2023-03-23 19:18 UTC, ccHanibal commented on src/main/java/com/myyearbook/hudson/plugins/confluence/ConfluenceSite.java
> +    public ConfluenceSite(URL url, final String credentialsId) {
Did most exactly that.

2023-03-23 19:19 UTC, ccHanibal commented on src/main/java/com/myyearbook/hudson/plugins/confluence/ConfluenceSite.java
> +
You are right. I was under the impression those were needed for XML serialisation. But they are not.

2023-03-23 19:20 UTC, ccHanibal commented on src/main/java/com/myyearbook/hudson/plugins/confluence/ConfluenceSite.java
> +                if (credentials instanceof UsernamePasswordCredentials) {
Now using StandardUsernamePasswordCredentials anyway ,to be consitent across all places where credentials are retrieved.

2023-03-23 19:21 UTC, ccHanibal commented
I addressed your suggestions. More to come tomorrow.

2023-03-24 17:40 UTC, jetersen requested changes

2023-03-24 17:40 UTC, jetersen commented on src/main/java/com/myyearbook/hudson/plugins/confluence/credentials/ConfluenceApiTokenImpl.java
> +public final class ConfluenceApiTokenImpl extends BaseStandardCredentials implements ConfluenceApiToken {
I don't think we need to implement our own credential implementation. I think we should just use StringCredentials 😓 Sorry I did not provide enough context.

Which you can get from depending on this plugin without a version since it is in the jenkins plugin BOM: https://plugins.jenkins.io/plain-credentials/ it is broadly installed.

https://github.com/search?q=plain-credentials+org%3Ajenkinsci&type=code

2023-03-27 08:10 UTC, ccHanibal commented on src/main/java/com/myyearbook/hudson/plugins/confluence/credentials/ConfluenceApiTokenImpl.java
> +public final class ConfluenceApiTokenImpl extends BaseStandardCredentials implements ConfluenceApiToken {
Hm yeah thought about that.
I got my instiration from the GitLab plugin which does both, implement its own type and support StringCredentials. And I though "we don't need both", but apparently I chose the "wrong" one.
Should be easy to change.

2023-03-27 08:35 UTC, jetersen commented on src/main/java/com/myyearbook/hudson/plugins/confluence/credentials/ConfluenceApiTokenImpl.java
> +public final class ConfluenceApiTokenImpl extends BaseStandardCredentials implements ConfluenceApiToken {
For newer implementation I would stick to StringCredentials unless there was a different need for multiple different string typed credentials.

2023-03-27 16:09 UTC, jetersen requested changes
One minor issue is the star imports. Once we fix those, this is ready.

2023-03-27 16:09 UTC, jetersen commented on src/main/java/com/myyearbook/hudson/plugins/confluence/ConfluenceSite.java
> +import com.cloudbees.plugins.credentials.*;
I would ask if you can undo the star imports.

2023-03-27 16:09 UTC, jetersen commented on src/main/java/com/myyearbook/hudson/plugins/confluence/ConfluenceSite.java
> +import hudson.model.*;
Ditto

2023-03-27 16:21 UTC, ccHanibal commented on src/main/java/com/myyearbook/hudson/plugins/confluence/ConfluenceSite.java
> +import com.cloudbees.plugins.credentials.*;
done

2023-03-27 16:21 UTC, ccHanibal commented on src/main/java/com/myyearbook/hudson/plugins/confluence/ConfluenceSite.java
> +import hudson.model.*;
done

2023-03-29 08:19 UTC, jetersen commented
@ccHanibal Did you have a chance to test the HPI and see if the token bearer worked?

https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/plugins/confluence-publisher/154.vef20e6e5fdd9/confluence-publisher-154.vef20e6e5fdd9.hpi

2023-03-29 09:49 UTC, ccHanibal commented
@jetersen Tested with my local build and with the v154 hpi. Also tested the automatic migration of username and password aufter upgrading. All looked good.

2023-03-29 10:05 UTC, jetersen approved these changes

2023-03-29 10:05 UTC, merged

2023-03-29 10:13 UTC, ccHanibal commented
Oh damn it.
Just noticed that I did not delete the resource file for rendering the custom ConfluenceApiTokenImpl (which has been removed): credentials/ConfluenceApiTokenImpl/credentials.jelly
I think we can just leave it in, but can cause potential irritations in the future.